[project]
name = "experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "colorama==0.4.6",
    "cvxpy>=1.8.1",
    "datasets==4.5.0",
    "deepeval==3.8.6",
    "einops==0.8.2",
    "huggingface-hub==0.36.2",
    "lightning==2.4.0",
    "lm-eval>=0.4.11",
    "matplotlib==3.10.8",
    "nemo>=7.2.5",
    "nemo-automodel>=0.2.0",
    "nemo-toolkit>=2.7.0",
    "numpy==2.4.2",
    "omegaconf==2.3.0",
    "polars==1.37.1",
    "pyarrow>=21.0.0",
    "pytest==9.0.2",
    "pyyaml==6.0.3",
    "scikit-learn>=1.8.0",
    "tensorboard>=2.20.0",
    "torchtext>=0.18.0",
    "torchvision>=0.24.0",
    "tqdm==4.67.3",
]

[tool.uv]
index-strategy = "unsafe-best-match"

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
