hydra:
  d_model: 768
  d_state: 64
  d_conv: 17              
  head_dim: 64
  expand: 2
  n_groups: 1
  # num_diffusion_steps: 100
  # vocab_size: 30000
  chunk_size: 256

guider:
  d_model: 768
  d_state: 64
  d_conv: 17
  head_dim: 64
  expand: 2
  n_groups: 1
  vocab_size: 30000
  chunk_size: 256

scheduler:
  d_model: 256
  vocab_size: 32000
  hidden_layers: 4
  max_steps: 100